[package]
name = "rs-simple-logging"
version = "0.2.0"
edition = "2021"
description = "Simple logging"
license = "Apache-2.0"
documentation = "https://docs.rs/crate/rs-simple-logging"
repository = "https://github.com/takanoriyanagitani/rs-simple-logging"

[dependencies]
